spring.application.name=blb

spring.datasource.url=jdbc:mysql://${DB_HOST}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=liquibase-changeLog.xml


jwt.secret: ${PASSCODDER}
jwt.lifetime: 432000000

spring.mail.username=cohort40.1.11@gmail.com
spring.mail.password=${MAILAPI}
spring.mail.host=smtp.gmail.com
spring.mail.port= 587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.context-path=/api

supabase.url=${SUPABASE_URL}
supabase.anon.public=${SUPABASE_ANON_PUBLIC}
supabase.service.role.secret=${SUPABASE_SERVICE_ROLE_SECRET}
supabase.bucket=${SUPABASE_BUCKET}

server.port=${PORT:8080}
